spring:
  application:
    name: cimb-wealth-backend
  
  profiles:
    active: dev
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/cimb_wealth}
    username: ${DATABASE_USERNAME:cimb_user}
    password: ${DATABASE_PASSWORD:cimb_password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    playground:
      enabled: true
      path: /playground
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
  
  security:
    jwt:
      secret: ${JWT_SECRET:cimb-wealth-super-secret-key-for-development-only-change-in-production}
      expiration: 86400000 # 24 hours
      refresh-expiration: 604800000 # 7 days

---
spring:
  config:
    activate:
      on-profile: dev
  
  datasource:
    url: jdbc:postgresql://localhost:5432/cimb_wealth_dev
    username: cimb_dev
    password: cimb_dev_password
  
  jpa:
    show-sql: true
  
  graphql:
    graphiql:
      enabled: true
    playground:
      enabled: true

logging:
  level:
    com.cimb.wealth: DEBUG
    org.springframework.security: DEBUG
    org.springframework.graphql: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod
  
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  
  jpa:
    show-sql: false
  
  graphql:
    graphiql:
      enabled: false
    playground:
      enabled: false

logging:
  level:
    com.cimb.wealth: INFO
    org.springframework.security: WARN
    org.springframework.graphql: WARN

---
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
