version: '3.9'
services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    image: node:18-alpine
    working_dir: /srv
    volumes:
      - ./server:/srv
    command: sh -c "npm i && node index.js"
    env_file:
      - .env
    ports:
      - "5000:5000"


